version: '3.8'
services:
  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
    volumes:
      - ./minio_data:/data
    networks:
      - ml_network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mlflowdb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d mlflowdb" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - ml_network

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.8.1
    command: >
      sh -c "pip install psycopg2-binary &&
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri postgresql://user:password@db:5432/mlflowdb
      --default-artifact-root s3://mlflow-artifacts/
      "
    ports:
      - "5001:5000"
    environment:
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: admin123
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started
    networks:
      - ml_network

  training:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=admin123
      - S3_ENDPOINT_URL=http://minio:9000
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - RAW_BUCKET=study-project-data
      - PROCESSED_BUCKET=study-project-data
    command: ["sleep", "infinity"]
    depends_on:
      - minio
      - mlflow
    networks:
      - ml_network

networks:
  ml_network:
    driver: bridge